# <font color='blue'>UNINOVE - Ciência de Dados</font>

## Tópico 11 - Python: Computação Científica com SciPy

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.7


<b>SciPy</b> é um conjunto de ferramentas open-source utilizadas principalmente para computação científica de alta performance. Os pacotes básicos de instalação do SciPy são: <i>NumPy, Matplotlib, Pandas, Sympy Nose, IPhyton e SciPy</i>.

https://scipy.org

### Matriz Inversa

In [2]:
# Importar as bibliotecas NumPy e SciPy
import numpy as np

https://scipy.github.io/devdocs/reference/linalg.html

In [3]:
from scipy import linalg

In [4]:
# Definindo matriz
A = np.array([[3, 0, 2],[9, 1, 7],[1, 0, 1]])
# Gerando a matriz inversa
Ainversa = linalg.inv(A)

In [5]:
print("Matriz A")
print(A)

Matriz: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 18 30]]


In [5]:
print("Matriz A inversa")
print(Ainversa)

Matriz A inversa
[[ 1.  0. -2.]
 [-2.  1. -3.]
 [-1.  0.  3.]]


Podemos agora tirar a prova real, ou seja, verificar se realmente a multiplicação da matriz A pela sua inversa é igual a matriz Identidade.

In [6]:
# Importar bibliotecas
import numpy as np
from scipy import linalg

# matriz
A = np.array([[3, 0, 2],[9, 1, 7],[1, 0, 1]])
# matriz inversa
Ainversa = linalg.inv(A)

In [7]:
# matrix identidade
B = A.dot(Ainversa)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Sistema de equações lineares

Agora suponha que tenhamos as seguintes equações: 

x + y  + z = 6

8x + 3y - z = 8

2x -3y + z = 12

In [8]:
# Importar bibliotecas
import numpy as np
from scipy import linalg

# Definindo matrizes
A = np.array([[1, 1, 1],[8, 3, -1],[2, -3, 1]])
B = np.array([[6],[8],[12]])

# Matriz inversa
Ainversa = linalg.inv(A)

# Matriz identidade
C = Ainversa.dot(B)

# Imprimindo valores calculados
print(C)
print("Valor da variável x:", C[0][0]);
print("Valor da variável y:", C[1][0]);
print("Valor da variável z:", C[2][0]);

[[ 2.]
 [-1.]
 [ 5.]]
Valor da variável x: 2.0
Valor da variável y: -1.0
Valor da variável z: 5.0


Outra forma de se resolver é utilizar a função <i>solve</i>.

https://scipy.github.io/devdocs/reference/generated/scipy.linalg.solve.html

In [9]:
# Importar bibliotecas
import numpy as np
from scipy import linalg

# Definido matrizes
A = np.array([[1, 1, 1],[8, 3, -1],[2, -3, 1]])
B = np.array([[6],[8],[12]])

# Calculando valor das variáveis da equação
C = np.linalg.solve(A, B)

print(C)
print("Valor da variável x:", C[0][0])
print("Valor da variável y:", C[1][0])
print("Valor da variável z:", C[2][0])

[[ 2.]
 [-1.]
 [ 5.]]
Valor da variável x: 2.0
Valor da variável y: -0.9999999999999998
Valor da variável z: 5.000000000000001


Note que houve uma pequena diferença de valores devido a questões de arredondamento. Caso necessário e desejado podemos usar a função <i>round</i> para arredondarmos valores decimais para o número de casas desejado.

Sintaxe: <i>round(valor_a_ser_arredondado, numero_de_casas_decimais)</i>

https://docs.python.org/3/library/functions.html#round

In [10]:
# Importar bibliotecas
import numpy as np
from scipy import linalg

# Definindo matrizes
A = np.array([[1, 1, 1],[8, 3, -1],[2, -3, 1]])
B = np.array([[6],[8],[12]])

# Calculando valor das variávies da equação
C = np.linalg.solve(A, B)

print(C)

# Resultados com arredondamento!!!
print("Valor da variável x:", round(C[0][0],2));
print("Valor da variável y:", round(C[1][0],2));
print("Valor da variável z:", round(C[2][0],2));

[[ 2.]
 [-1.]
 [ 5.]]
Valor da variável x: 2.0
Valor da variável y: -1.0
Valor da variável z: 5.0


### Determinante

Utilizado com grande frequencia em álgebra linear. Aplica-se a matrizes quadradas, ou seja, que tem mesma quantidade de linhas e colunas.

In [11]:
# Importar bibliotecas
import numpy as np
from scipy import linalg

# Definindo matrizes
A = np.array([[8]])
B = np.array([[4,2],[3,3]])
C = np.array([[1,4,2],[1,3,3],[2,6,1]])

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.det.html

In [12]:
# Matriz de ordem 1
print("Matriz A")
print (A)

# Calculando o Determinante
print("Determinante de A")
Res = round(np.linalg.det(A),2)
print(Res)

Matriz A
[[8]]
Determinante de A
8.0


In [13]:
# Matriz ordem 2
print("Matriz B")
print (B)

print("Determinante de B")
Res = round(np.linalg.det(B),2)
print(Res)

Matriz B
[[4 2]
 [3 3]]
Determinante de B
6.0


In [14]:
# Matriz ordem 3
print("Matriz C")
print (C)
print("Determinante de C")
Res = round(np.linalg.det(C),2)
print(Res)

Matriz C
[[1 4 2]
 [1 3 3]
 [2 6 1]]
Determinante de C
5.0
