# <font color='blue'>UNINOVE - Ciência de Dados</font>

## Tópico 09 - Python: Vetores (NumPy)

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.7


### Criando vetores em NumPy - https://numpy.org

In [2]:
# Importar a biblioteca NumPy.
import numpy as np

In [3]:
# Exemplo de um vetor NumPy.
vetor = np.array( [8, 34, 67, 98] )

In [4]:
# Imprimindo dados do vetor
print(vetor)

[ 8 34 67 98]


<b>shape</b> - informa a quantidade de colunas de um vetor. Caso seja uma matriz de muitas dimensões (multidimensional), indicará as dimensões da matriz multidimensional.

In [5]:
print('Shape:',vetor.shape)

Shape: (4,)


<b>dtype</b> - indicará qual o tipo de dado dos valores armazenados no vetor.

In [6]:
print('Dtype:',vetor.dtype)

Dtype: int64


<b>size</b> - retorna a quantidade de elementos do vetor e/ou matriz.

In [7]:
print('Size:',vetor.size)

Size: 4


<b>itemsize</b> - retorna o tamanho de um elemento da matriz em bytes.

In [8]:
print('Itemsize:',vetor.itemsize)

Itemsize: 8


<b>ndim</b> - retornará o número de dimensões da matriz.

In [9]:
print('Ndim:', vetor.ndim)

Ndim: 1


In [10]:
# exemplo com float 
vetor = np.array([8.87, 34, 67.89, 98,1.09])
 
# Imprimindo dados do vetor
print(vetor)
print('Shape:',vetor.shape)
print('Dtype:',vetor.dtype)
print('Size:',vetor.size)
print('Itemsize:',vetor.itemsize)
print('Ndim:', vetor.ndim)

[ 8.87 34.   67.89 98.    1.09]
Shape: (5,)
Dtype: float64
Size: 5
Itemsize: 8
Ndim: 1


### Acessando e alterando vetores

Assim como nas listas podemos acessar elementos particulares no vetor como também podemos alterar seus valores. Para isso devemos usar o índice dos mesmos, lembrando que o primeiro elemento tem índice igual a 0 e assim sucessivamente. 

In [11]:
import numpy as np
 
vetor = np.array([8, 34, 67, 98] )
# imprimindo elementos na posção 0 e 2
print('Vetor posicao 0:',vetor[0])
print('Vetor posicao 2:',vetor[2])

# alterando o valor dos elementos 1 e 3
vetor[1] = 231
vetor[3] = 105
# imprimindo o novo vetor
print(vetor)

Vetor posicao 0: 8
Vetor posicao 2: 67
[  8 231  67 105]


### Criação de vetores

Podemos também criar vetores vazios, com valores igual a zero, com valores igual a 1, com valores uniformemente distribuídos ou com valores aleatórios (dentro de intervalos que podemos pré-determinar).

In [12]:
# importar biblioteca NumPy
import numpy as np

<i>empty(quantidade_de_elementos, tipo_de_dados)</i>: criar matriz com valores vazios.

In [13]:
vetor01 = np.empty(10,int)
print(vetor01)

[                  0                   0                   0
                   0     139633681760256 7003205409869740082
 3545508526067901229 3258692105440945462 4049079336931714105
     139634490434099]


Note que ao criar um vetor com 10 elementos <b>vazios</b> foram atribuídos valores quaisquer ao mesmo. O ideal, ao se criar um vetor, que se inicie com zeros ou uns.

<i>zeros(quantidade_de_elementos, tipo_de_dados)</i>: criar matriz com valores igual a zero.

In [14]:
vetor02 = np.zeros(10)
print(vetor02)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


<i>ones(quantidade_de_elementos, tipo_de_dados)</i>: criar matriz com valores igual a 1.

In [15]:
vetor03 = np.ones(10)
print(vetor03)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


<i>arange(valor_inicial, valor_de_parada, passo, tipo_de_dados)</i>: criar matriz com valores uniformemente distribuídos.

<ul>
    <li><b>valor_inicial</b>: valor de início do intervalo. O valor padrão é 0.</li>
    <li><b>valor_de_parada</b>: enquanto for menor que este valor os valores são incluiídos na matriz.</li>
    <li><b>passo</b>: o espaçamento entre os valores. O valor padrão é 1.</li>
    <li><b>tipo_de_dados</b>: o tipo de saída dos dados. Se não for especificado, o tipo de dados será o mesmo que o do valor inicial</li>
<ul>

In [16]:
vetor04 = np.arange(3,13,2,float);
print(vetor04)

[ 3.  5.  7.  9. 11.]


<i>random.random(quantidade_de_elementos)</i>: gerar número randômico, ponto flutuante, entre 0 e 1.

O campo <b>tipo_de_dados</b> é opcional.

In [17]:
vetor05 = 6*np.random.random(5);
print(vetor05)

[0.79732026 0.44690421 3.09400329 0.94209644 2.95930311]
