# <font color='blue'>UNINOVE - Ciência de Dados</font>

## Tópico 10 - Python: Matrizes (NumPy)

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.7


### Criando matrizes em NumPy - https://numpy.org

In [2]:
# Importar a biblioteca NumPy.
import numpy as np

In [3]:
# Exemplo de uma matriz NumPy
matriz = np.array([[1,2,3],[4,5,6],[7,8,9],[10,20,30]])

In [4]:
# Imprimindo dados do vetor
print('Matriz:',matriz)
print('Elemento posicao (1,2):',matriz[1][2])
print('Dimensoes:',matriz.ndim)

Matriz: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
Elemento posicao (1,2): 6
Dimensoes: 2


In [5]:
# Atribuindo valor a um elemento da matriz
matriz[3][1] = 18
print('Matriz:',matriz)

Matriz: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 18 30]]


### Operações matemáticas com matrizes

In [6]:
# Importar biblioteca
import numpy as np

# Definindo as matrizes
matriz01 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,20,30]])
matriz02 = np.array([[2,2,2], [6,9,-10], [1,7,9] , [3,6,8]])
matriz03 = np.array([[1,1], [0,4],[2,2]])

In [7]:
# Soma 
matrizsoma= matriz01 + matriz02
# Subtração
matrizsub = matriz01 - matriz02

Função para efetuar multiplicação de matrizes: </b>dot</b> - https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [8]:
matrizprod = matriz01.dot(matriz03)

#### Imprimindo as matrizes

In [9]:
print('Matriz 01')
print(matriz01)

Matriz 01
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]


In [10]:
print('Matriz 02')
print(matriz02)

Matriz 02
[[  2   2   2]
 [  6   9 -10]
 [  1   7   9]
 [  3   6   8]]


In [11]:
print('Matriz 03')
print(matriz03)

Matriz 03
[[1 1]
 [0 4]
 [2 2]]


In [12]:
print('Soma Matriz 01 + Matriz 02')
print(matrizsoma)

Soma Matriz 01 + Matriz 02
[[ 3  4  5]
 [10 14 -4]
 [ 8 15 18]
 [13 26 38]]


In [13]:
print('Subtracao Matriz 01 - Matriz 02')
print(matrizsub)

Subtracao Matriz 01 - Matriz 02
[[-1  0  1]
 [-2 -4 16]
 [ 6  1  0]
 [ 7 14 22]]


In [14]:
print('Produto Matriz 01 x Matriz 03')
print(matrizprod)

Produto Matriz 01 x Matriz 03
[[  7  15]
 [ 16  36]
 [ 25  57]
 [ 70 150]]


Podemos <b>concatenar</b> e <b>dividir</b> matrizes para isso temos as funções <i>concatenate</i> e <i>split</i>.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

https://numpy.org/doc/stable/reference/generated/numpy.split.html

### Concatenação de matrizes

In [15]:
# Importar biblioteca
import numpy as np

# Definir matrizes
matriz01 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,20,30]])
matriz02 = np.array([[2,2,2], [6,9,-10], [1,7,9] , [3,6,8]])
matriz03 = np.zeros((1,3))

# Concatenando matrizes
matrizresultante = np.concatenate((matriz01,matriz02,matriz03))

In [16]:
print('Matriz 01')
print(matriz01)

Matriz 01
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]


In [17]:
print('Matriz 02')
print(matriz02)

Matriz 02
[[  2   2   2]
 [  6   9 -10]
 [  1   7   9]
 [  3   6   8]]


In [18]:
print('Matriz 03')
print(matriz03)

Matriz 03
[[0. 0. 0.]]


In [19]:
print('Matriz Concetenada')
print(matrizresultante)

Matriz Concetenada
[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  20.  30.]
 [  2.   2.   2.]
 [  6.   9. -10.]
 [  1.   7.   9.]
 [  3.   6.   8.]
 [  0.   0.   0.]]


### Divisão de matrizes - <i>split</i>

Uma observação importantes a ser feita com a utilização da função <i>split</i>. Ela irá apresentar erro caso a quantidade de linhas na matriz resultante não seja exatamente igual em cada uma das partes em que a matriz foi dividida. 

In [20]:
# Importar biblioteca
import numpy as np

# Definir matriz
matriz01 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,20,30]])

# Split 
matrizresultante = np.split(matriz01,2)

In [21]:
# Imprimindo matrizes
print('Matriz 01')
print(matriz01)

Matriz 01
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]


In [22]:
print('Matriz Resultante parte 1')
print(matrizresultante [0])

Matriz Resultante parte 1
[[1 2 3]
 [4 5 6]]


In [23]:
print('Matriz Resultante parte 2')
print(matrizresultante [1])

Matriz Resultante parte 2
[[ 7  8  9]
 [10 20 30]]


### Matriz Transposta

Matriz transposta é aquela que é obtida efetuando-se a troca de linhas por colunas de uma dada matriz.

https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

In [24]:
# Importar biblioteca
import numpy as np

# Definindo matriz
matriz = np.array([[10, 20],[30,40],[50,60],[70,80]])

# Gerando a matriz transposta
matrizt = matriz.transpose()

In [25]:
print('Matriz')
print(matriz)

Matriz
[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [26]:
print('Matriz transposta')
print(matrizt)

Matriz transposta
[[10 30 50 70]
 [20 40 60 80]]


### Operações matemáticas interessantes com matrizes

In [27]:
# Importar biblioteca
import numpy as np

# Definido matriz
matriz = np.array([[1,2,3],[4,5,6],[7,8,9],[10,20,33]])

<b>max()</b>: recupera o maior elemento da matriz.

https://numpy.org/doc/stable/reference/generated/numpy.matrix.max.html

In [28]:
print('Max:',matriz.max())

Max: 33


<b>min()</b>: recupera o menor elemento da matriz.

https://numpy.org/doc/stable/reference/generated/numpy.matrix.min.html

In [29]:
print('Min:',matriz.min())

Min: 1


<b>ptp()</b>: apresenta a diferença entre o maior elemento da matriz e o menor elemento da matriz.

https://numpy.org/doc/stable/reference/generated/numpy.ptp.html

In [30]:
print('Ptp:',matriz.ptp())

Ptp: 32


<b>sum()</b>: soma os elementos de uma matriz.

https://numpy.org/doc/stable/reference/generated/numpy.sum.html

In [31]:
print('Sum:',matriz.sum())

Sum: 108


<b>mean()</b>: média aritmética entre os elementos da matriz.

https://numpy.org/doc/stable/reference/generated/numpy.mean.html

In [32]:
print('Mean:',matriz.mean())

Mean: 9.0


<b>var()</b>: variância entre os elementos da matriz.

https://numpy.org/doc/stable/reference/generated/numpy.var.html

In [33]:
print('Var:',matriz.var())

Var: 75.16666666666667


<b>std()</b>: variância entre os elementos da matriz.

https://numpy.org/doc/stable/reference/generated/numpy.std.html

In [34]:
print('Std:',matriz.std())

Std: 8.669871202426636


Podemos redimensionar nossas matrizes com o uso da função <i>resize</i> ou <i>reshape</i>. A diferença entre as duas abordagens é:

<ul>
    <li><b>reshape</b> não altera a matriz original enquanto que <b>resize</b> altera a matriz original.</li>
    <li><b>reshape</b> tem que manter a mesma quantidade de elementos na matriz enquanto que no <b>resize</b> não existe esta obrigatoriedade.</li>
</ul>

Por exemplo, uma matriz 3x3 (3 linhas e 3 colunas - 9 elementos) não pode ser feito o <i>reshape</i> para 2x5 pois neste caso teríamos 10 elementos, 1 a mais do que na matriz original. Para <i>resize</i> não há problema algum em se efetuar o resize de uma matriz 3x3 para uma matriz 2x5.

In [35]:
# Importar biblioteca
import numpy as np

# Definindo matriz
matriz = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [36]:
# Imprimindo matrizes
print ('matriz antes do Reshape')
print(matriz)

matriz antes do Reshape
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [37]:
print('Reshape')
print(matriz.reshape(5,3));

Reshape
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [38]:
print ('matriz após Reshape')
print(matriz)

matriz após Reshape
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [39]:
print('Efetuar Resize')
matriz.resize(8,2)

Efetuar Resize


In [40]:
print('Matriz após resize')
print(matriz)

Matriz após resize
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15  0]]
